# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [2]:
import pandas as pd
import numpy as np

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [3]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data=data)

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [5]:
age_data = df.Age
age_data

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [8]:
df["Salary"] = [50000, 60000, 45000]
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [9]:
filtered_by_age_18 = df[df["Age"] > 18]
filtered_by_age_18

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [21]:
from datetime import datetime

df["Birth year"] = datetime.now().year - df["Age"]
df

    Name  Age         City  Salary  Birth year  Average age  Diff
0   John   16     New York   50000        2009         22.0   6.0
1  Emily   28  Los Angeles   60000        1997         22.0   6.0
2   Ryan   22      Chicago   45000        2003         22.0   0.0

### Task 4.2

Add new calculated field `Average age`.

In [12]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   60000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [23]:
df["Diff"] = abs(df["Age"] - df["Average age"])
df

    Name  Age         City  Salary  Birth year  Average age  Diff
0   John   16     New York   50000        2009         22.0   6.0
1  Emily   28  Los Angeles   60000        1997         22.0   6.0
2   Ryan   22      Chicago   45000        2003         22.0   0.0

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [26]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data=data1)
df2 = pd.DataFrame(data=data2)

In [32]:
merge_df = pd.merge(df1, df2, left_on="Name", right_on="Name")
merge_df

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [33]:
concat_df = pd.concat([df1, df2])
concat_df

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [35]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [38]:
summa = s1 + s2
summa

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [40]:
diff = s2 - s1
diff

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [41]:
multiplication = s1 * s2
multiplication

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [44]:
division = s2 / s1
division

0    6.000000
1    3.500000
2    2.666667
3    2.250000
4    2.000000
dtype: float64

In [45]:
pow_operation = s1 ** s2
pow_operation

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [46]:
integer_division = s2 // s1
integer_division

0    6
1    3
2    2
3    2
4    2
dtype: int64

In [47]:
modulus = s2 % s1
modulus

0    0
1    1
2    2
3    1
4    0
dtype: int64

In [50]:
s1_filtered_even = s1.loc[lambda x: x % 2 == 0]
s1_filtered_even

1    2
3    4
dtype: int64

In [51]:
s2_filtered_odd = s2[s2 % 2 != 0]
s2_filtered_odd

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [56]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [67]:
s_upper = s.str.upper()
s_upper

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [59]:
s_length = s.str.len()
s_length

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [63]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 8.83 s
Wall time: 9.14 s

[49.4, 46.0, 45.6, 36.2, 32.0, 21.8, 35.4, 30.6, 31.8, 40.2]

### Solution using Pandas and Numpy

In [66]:
import random

def unknown_signature_pandas():
    # Generate a large dataset
    s = pd.Series([random.randint(1, 100) for _ in range(10000000)])

    # Calculate the moving average with a window of 5
    moving_averages = s.rolling(window=5).mean().dropna().reset_index(drop=True)
    
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 8.19 s
Wall time: 9.06 s

[35.8, 24.6, 37.4, 48.0, 41.4, 55.4, 60.0, 51.8, 55.8, 59.8]